---
:event: i45
:secret: b5f6f7f1ed04aeeeea93d5a8291e52d6
:postable_types:
  - :type: TOURNEY
    :desc: Tournament Announcement
  - :type: TANNOY
    :desc: Tannoy Announcement
  - :type: SERVICE
    :desc: viewr Service Announcement
  - :type: GENERAL
    :desc: General Announcement
:feeds:
  - :type: TwitterPoller
    :details: iseries
  - :type: TwitterPoller
    :details: MPLAY_Wizzo
  - :type: NewsPoller
    :details: http://iseries.multiplay.co.uk/news/i45/feed/rss/
  - :type: ForumPoller
    :details: http://forums.multiplay.co.uk/external.php?type=RSS2&forumid=332
