defaults: &defaults
  adapter: mysql
  database: mpuk
  username: root
  host: localhost

development:
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/viewr_test.db
  <<: *defaults
production:
  <<: *defaults
