---
chdir: /data/mpuk/viewr
environment: development
address: 0.0.0.0
port: 3000
servers: 1
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
daemonize: true
